### ISSUE TITLE
add info about 'beans.xml' requirement

### ISSUE THREAD

**Issue by jgangemi** [shillner/maven-cdi-plugin-utils#17]
let's try this again...

it looks like a `beans.xml` file is required for the plugin to locate `CDIMojoProcessingStep` implementations. if this is accurate (i'm trying to create my own maven plugin using these utils), it would probably be good to add mention of this to the `README`.

if it's not, is there a reason my steps aren't found w/o it?

**Comment by jgangemi** [comment]
sorry - wrong project

**Comment by shillner** [comment]
I added a note in the [Getting Startet Guide](https://github.com/shillner/maven-cdi-plugin-utils/wiki/Getting-Started#2-add-beansxml).

beans.xml is required at the moment but I will investigate if it can be omitted in any way.
