### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by andye2004** [shillner/maven-cdi-plugin-utils#27]
I understand why you've wrapped the maven logger, but maven uses sl4j so why not just inject standard slf4j implemented loggers?

**Comment by bannmann** [comment]
I was going to file this exact same issue. SLF4J `Logger` even includes `isDebugEnabled()` etc, so there's virtually no reason to keep all the code passing around Maven plexus `Log` instances. I ripped that out of my plugins and feel much better :-)

@shillner, what do you think?

**Comment by bannmann** [comment]
I discovered that the stuff added by `MavenLogWrapper` was not really needed:

- `isDebugEnabled()` etc and `setContextClass()`  did not end up being used
- `enableLogTimestamps()` is redundant with standard SLF4J `SimpleLogger` capabilities

I filed PR #31 to switch to SLF4J.

As a welcome side effect of that patch, mojo authors can suppress INFO messages like `Constructing workflow for processing` and `Goal 'mymojo:mygoal' will use default workflow packaged with the plugin.` like this:

```java
public final class MyMojo extends AbstractCDIMojo
{
    static
    {
        System.setProperty("org.slf4j.simpleLogger.log.com.itemis.maven.plugins.cdi", "warn");
    }
```
